const ShopActionTypes = {
    FETCH_COLLECTIONS_START : 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS : 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURES : 'FETCH_COLLECTIONS_FAILURES'
}

export default ShopActionTypes;

