export const SHOP_DATA = [
    {
        id:1,
        name:"Nikon",
        imageUrl:"https://www.jing.fm/clipimg/full/136-1361384_impact-ergonomic-backpack-ipeg-130-pink-school-bags.png",
        price:499
    },
    {
        id:2,
        name:"Demo",
        imageUrl:"https://www.pngkit.com/png/full/87-875396_school-bag-png-background-image-school-bag-images.png",
        price:300
    }
    ,{
        id:3,
        name:"Demo",
        imageUrl:"https://www.pngkit.com/png/full/87-875396_school-bag-png-background-image-school-bag-images.png",
        price:300
    }
    ,{
        id:4,
        name:"Demo",
        imageUrl:"https://www.pngkit.com/png/full/87-875396_school-bag-png-background-image-school-bag-images.png",
        price:300
    }
    ,{
        id:5,
        name:"Demo",
        imageUrl:"https://www.pngkit.com/png/full/87-875396_school-bag-png-background-image-school-bag-images.png",
        price:300
    }
    ,{
        id:6,
        name:"Nikyy",
        imageUrl:"https://pngimg.com/uploads/backpack/backpack_PNG6321.png",
        price:300
    }
]

